FROM python:3.7-alpine
RUN apk add build-base python-dev py-pip jpeg-dev zlib-dev
ENV LIBRARY_PATH=/lib:/usr/lib
WORKDIR /opt/app
COPY requirements.txt .
COPY FirstSteps.py .
COPY data.json .
RUN pip install -r requirements.txt
CMD ["python", "FirstSteps.py"]
